server:
  port: 8001
  servlet:
    context-path: /api/core/*

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/core
    username: ${DB_USER:core_dbu}
    password: ${DB_PASS:pass}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:root}
    password: ${RABBITMQ_PASSWORD:root}
    listener:
      type: simple
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 10
          max-interval: 600000
        acknowledge-mode: auto
