version: "3.7"
services:
  db-core:
    image: postgres:13
    container_name: db-core
    environment:
      - POSTGRES_USER=core_dbu
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=core
    ports:
      - 5432:5432

  mq:
    image: registry.hub.docker.com/library/rabbitmq:3.7-management
    container_name: rabbit-mq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672

  core-service:
    build: .
    container_name: core-service
    environment:
        - DB_HOST=db-core
        - DB_PORT=5432
        - DB_USER=core_dbu
        - DB_PASS=pass
        - RABBITMQ_HOST=mq
    ports:
      - 8000:8000
